name: greedymax-env
dependencies:
  - python=3.9.*
  - astropy
  - hypothesis
  - matplotlib
  - more-itertools
  - numpy=1.21.*
  - openpyxl
  - pytest
  - pytz
  - tabulate
  - tqdm
  - scipy
  - coverage
  - requests
  - graphene-django
