site_name: GPP Scheduler
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo@2x.svg
  icon:
    admonition:
      todo: material/clipboard-check-outline
  palette:
    - primary: black
    - accent: amber
    #  Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: black
      accent: amber
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

nav:
  - Getting Started: getting-started.md
  - Architecture: architecture.md
  - Core Components:
      - core-components/events.md
  - External Services:
      - external-services/index.md
      - external-services/resource.md


markdown_extensions:
  - pymdownx.superfences:
        # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - admonition

plugins:
  - search
  - mermaid2
  - mkdocstrings:
      handlers:
        python:
          inventories:
            - https://docs.python.org/3/objects.inv
            - https://docs.astropy.org/en/stable/objects.inv
            - https://numpy.org/doc/stable/objects.inv
          options:
            show_root_heading: true
            show_root_toc_entry: true
            separate_signature: false
            show_symbol_type_heading: true
            signature_crossrefs: true
            merge_init_into_class: true
            docstring_section_style: spacy
            inherited_members: true
            members_order: source
            unwrap_annotated: true
            show_labels: false
            show_source: false



