collector:
  observation_classes: [SCIENCE, PROGCAL, PARTNERCAL]
  program_types: [Q, LP, FT, DD]
  time_slot_length: 1.0 # on minutes
  with_redis: false

optimizer:
  name: GREEDYMAX

selector:
  buffer_type: FLAT_MINUTES
  buffer_amount: 30.0

server:
  port: 8000
  host: 0.0.0.0

app:
  version: 0.0.0
  changelog:
    - Added server versioning and changelog
    - Added schema to send version to client
