mode: VALIDATION # Modes: Validation, Simulation, Operation

sources:
  environment: MOCK
  resource: MOCK

process_manager: 
  size: 5 # Only valid for Simulation and Validation 
  timeout: 100

collector:
  semesters: [2018B]
  observation_classes: [SCIENCE, PROGCAL, PARTNERCAL]
  program_types: [Q, LP, FT, DD]
  sites: ALL_SITES # Sites: GS, GN, ALL_SITES
  time_slot_length: 1.0 # on minutes

optimizer:
  name: DUMMY

server:
  port: 8000
  host: 0.0.0.0
